CREATE TABLE IF NOT EXISTS plugin_delivery_pizza_state (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
cellnumber BIGINT UNSIGNED,
state VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_bin,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS plugin_delivery_pizza_operations_menu (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
menu_option INTEGER UNSIGNED,
codename VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_bin,
description VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_bin,
uploaded_menu_filename_media VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_bin,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;


CREATE TABLE IF NOT EXISTS plugin_delivery_pizza_customer_data (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
cellnumber BIGINT UNSIGNED UNIQUE,
name VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_bin,
email VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin,
cep VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_bin,
bairro VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_bin,
cidade VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_bin,
estado VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_bin,
complemento VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_bin,
referencia VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_bin,
telfixo VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin,
name_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS plugin_delivery_pizza_alternative_address (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
cellnumber BIGINT UNSIGNED,
full_data VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
inserted TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;