CREATE TABLE IF NOT EXISTS plugin_subscription (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
cellnumber BIGINT UNSIGNED,
name VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_bin,
email VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS plugin_subscription_runtime_messages (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
ask_for_name_or_not VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_bin,
ask_for_email_or_not VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_bin,
enter_your_name VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_bin,
enter_your_email VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_bin,
subscription_keyword VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_bin,
unknown_input VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_bin,
name_saved VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_bin,
finished_subscription VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_bin,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS plugin_subscription_state (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
cellnumber BIGINT UNSIGNED,
state VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_bin,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
