CREATE TABLE IF NOT EXISTS api_token (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
username VARCHAR(20) NOT NULL UNIQUE,
token VARCHAR(100) NOT NULL UNIQUE,
enabled BOOL NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
mongodb_name VARCHAR(30) NOT NULL UNIQUE,
phone BIGINT NOT NULL UNIQUE,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;