CREATE TABLE IF NOT EXISTS plugin_phishing (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
cellnumber BIGINT UNSIGNED UNIQUE,
answered INTEGER UNSIGNED,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS plugin_phishing_message (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
created_by BIGINT UNSIGNED,
message VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

