CREATE TABLE IF NOT EXISTS user_info (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
username VARCHAR(50) NOT NULL UNIQUE,
firstname VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
lastname VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
email VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
robot_cellnumber BIGINT UNSIGNED NOT NULL,
password VARCHAR(50) NOT NULL,
active BOOL NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS plugin (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
codename VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
description VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS node_plugin_control (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
node_name VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
node_is_plugin BOOL,
plugin_id INTEGER UNSIGNED,
PRIMARY KEY(id),
FOREIGN KEY (plugin_id) REFERENCES plugin(id) ON DELETE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS basic_conversation_plugin_main(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
presentation_message VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
goodbye_message VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
last_leaf_message VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
alias_found_message VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
multiple_keywords_matched_message VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
multiple_aliases_found_message VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
default_unknown_input_message VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
back_to_root_keyword VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_bin,
PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS basic_conversation_plugin_nodes_messages(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
graph_node_name VARCHAR(30),
graph_node_message VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS basic_conversation_plugin_nodes_aliases(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
bcpnm_id INTEGER UNSIGNED NOT NULL,
graph_node_alias VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_bin,
PRIMARY KEY (id),
CONSTRAINT C FOREIGN KEY (bcpnm_id) REFERENCES basic_conversation_plugin_nodes_messages(id) ON DELETE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS session(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
visitor_cellnumber BIGINT UNSIGNED,
first_ever_hello TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
last_started_session TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
last_message TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
graph_position VARCHAR(30),
PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS session_config(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
session_timeout_seconds BIGINT UNSIGNED,
record_chat BOOL,
record_chat_days INT UNSIGNED,
days_visitor_is_known INT UNSIGNED,
PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS message_log(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
visitor_cellnumber BIGINT UNSIGNED,
visitor_msg VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
robot_cellnumber BIGINT UNSIGNED,
robot_msg VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;