CREATE TABLE IF NOT EXISTS plugin_auth (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
administrator_cellnumber BIGINT UNSIGNED UNIQUE,
name VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_bin,
perm_id INTEGER UNSIGNED,
being_added_by BIGINT UNSIGNED,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS plugin_auth_perm_levels (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
description VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS plugin_auth_messages (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
access_granted VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
access_denied VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_bin,
PRIMARY KEY(id)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
